config/routes.rb
ComicCompass::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :shops

  root 'shops#index'

  get 'search' => 'shops#query'

end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#

class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/shop.rb
# == Schema Information
#
# Table name: shops
#
#  id                   :integer          not null, primary key
#  company              :string(255)
#  address              :string(255)
#  address2             :string(255)
#  city                 :string(255)
#  state                :string(255)
#  scf                  :string(255)
#  zip                  :string(255)
#  zip4                 :string(255)
#  mailscore            :string(255)
#  sic1code             :string(255)
#  sic1                 :string(255)
#  sic2code             :string(255)
#  sic2                 :string(255)
#  sic3code             :string(255)
#  sic3                 :string(255)
#  sic4code             :string(255)
#  sic4                 :string(255)
#  latitude             :float
#  longitude            :float
#  created_at           :datetime
#  updated_at           :datetime
#  email                :string(255)
#  phone                :string(255)
#  foursquare_id        :string(255)
#  url                  :string(255)
#  contact_person       :string(255)
#  contact_person_email :string(255)
#  facebook             :string(255)
#  twitter              :string(255)
#

class Shop < ActiveRecord::Base

	validates :company, :address, :city, :state, :zip, presence: true
	validates :state, length: { is: 2 }
	validates :zip, length: { is: 5 }
	validates :zip4, length: { is: 4 }

	geocoded_by :address_str

	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? } 

def address_str
  [self.address, self.city, self.state, 'US'].compact.join(', ')
end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, :except => [:index, :show, :query]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shop }
      else
        format.html { render action: 'new' }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end

  def query
    if (params[:latitude] == nil)
      return render :status => :bad_request, :text => "Missing required parameter latitude"
    elsif  (params[:longitude] == nil)
      return render :status => :bad_request, :text => "Missing required parameter longitude"
    end

    @shops = Shop.near([params[:latitude], params[:longitude]], 20) 
    respond_to do |format|
      format.html { render action: 'index'}
      format.json { render json: @shops }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:company, :address, :address2, :city, :state, :scf, :zip, :zip4, :mailscore, :sic1code, :sic1, :sic2code, :sic2, :sic3code, :sic3, :sic4code, :sic4, :latitude, :longitude)
    end

    def admin?
        false
    end

    def authorize
        unless  admin?
            flash[:error] = "Unauthorized access"
            redirect_to shops_url 
            false
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ComicCompass</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
<%= yield %>

</body>
</html>

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :scf %><br>
    <%= f.text_field :scf %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :zip4 %><br>
    <%= f.text_field :zip4 %>
  </div>
  <div class="field">
    <%= f.label :mailscore %><br>
    <%= f.text_field :mailscore %>
  </div>
  <div class="field">
    <%= f.label :sic1code %><br>
    <%= f.text_field :sic1code %>
  </div>
  <div class="field">
    <%= f.label :sic1 %><br>
    <%= f.text_field :sic1 %>
  </div>
  <div class="field">
    <%= f.label :sic2code %><br>
    <%= f.text_field :sic2code %>
  </div>
  <div class="field">
    <%= f.label :sic2 %><br>
    <%= f.text_field :sic2 %>
  </div>
  <div class="field">
    <%= f.label :sic3code %><br>
    <%= f.text_field :sic3code %>
  </div>
  <div class="field">
    <%= f.label :sic3 %><br>
    <%= f.text_field :sic3 %>
  </div>
  <div class="field">
    <%= f.label :sic4code %><br>
    <%= f.text_field :sic4code %>
  </div>
  <div class="field">
    <%= f.label :sic4 %><br>
    <%= f.text_field :sic4 %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<h1>Listing shops</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Address</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Scf</th>
      <th>Zip</th>
      <th>Zip4</th>
      <th>Mailscore</th>
      <th>Sic1code</th>
      <th>Sic1</th>
      <th>Sic2code</th>
      <th>Sic2</th>
      <th>Sic3code</th>
      <th>Sic3</th>
      <th>Sic4code</th>
      <th>Sic4</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.company %></td>
        <td><%= shop.address %></td>
        <td><%= shop.address2 %></td>
        <td><%= shop.city %></td>
        <td><%= shop.state %></td>
        <td><%= shop.scf %></td>
        <td><%= shop.zip %></td>
        <td><%= shop.zip4 %></td>
        <td><%= shop.mailscore %></td>
        <td><%= shop.sic1code %></td>
        <td><%= shop.sic1 %></td>
        <td><%= shop.sic2code %></td>
        <td><%= shop.sic2 %></td>
        <td><%= shop.sic3code %></td>
        <td><%= shop.sic3 %></td>
        <td><%= shop.sic4code %></td>
        <td><%= shop.sic4 %></td>
        <td><%= shop.latitude %></td>
        <td><%= shop.longitude %></td>
        <td><%= link_to 'Show', shop %></td>
        <!--<td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Shop', new_shop_path %>-->

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @shop.company %>
</p>

<p>
  <strong>Address:</strong>
  <%= @shop.address %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @shop.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @shop.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @shop.state %>
</p>

<p>
  <strong>Scf:</strong>
  <%= @shop.scf %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @shop.zip %>
</p>

<p>
  <strong>Zip4:</strong>
  <%= @shop.zip4 %>
</p>

<p>
  <strong>Mailscore:</strong>
  <%= @shop.mailscore %>
</p>

<p>
  <strong>Sic1code:</strong>
  <%= @shop.sic1code %>
</p>

<p>
  <strong>Sic1:</strong>
  <%= @shop.sic1 %>
</p>

<p>
  <strong>Sic2code:</strong>
  <%= @shop.sic2code %>
</p>

<p>
  <strong>Sic2:</strong>
  <%= @shop.sic2 %>
</p>

<p>
  <strong>Sic3code:</strong>
  <%= @shop.sic3code %>
</p>

<p>
  <strong>Sic3:</strong>
  <%= @shop.sic3 %>
</p>

<p>
  <strong>Sic4code:</strong>
  <%= @shop.sic4code %>
</p>

<p>
  <strong>Sic4:</strong>
  <%= @shop.sic4 %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @shop.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @shop.longitude %>
</p>

<!--<%= link_to 'Edit', edit_shop_path(@shop) %> |-->
<%= link_to 'Back', shops_path %>